name = "mage"
description = "Mini Ada Game Engine - A very simple game engine written in Ada"
version = "0.2.0"

website = "www.gitlab.com/leogermond/mage"

authors = ["Leo Germond"]
maintainers = ["Leo Germond <germond@adacore.com>"]
maintainers-logins = ["leogermond"]

licenses = "Apache-2.0"
tags = ["game", "engine", "sdl"]
[[depends-on]]
sdlada = "^2.5.4-1"

[origin]
commit = "c1398a48b8017f7ceae94e1ef1e162fb7c31b438"
url = "git+https://gitlab.com/leogermond/mage.git"

